{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "ename": "ConfigurationError",
     "evalue": "The resolution lifetime expired after 21.607 seconds: Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mLifetimeTimeout\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymongo/srv_resolver.py:97\u001b[0m, in \u001b[0;36m_SrvResolver._resolve_uri\u001b[0;34m(self, encapsulate_errors)\u001b[0m\n\u001b[1;32m     96\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> 97\u001b[0m     results \u001b[39m=\u001b[39m _resolve(\n\u001b[1;32m     98\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39m_\u001b[39;49m\u001b[39m\"\u001b[39;49m \u001b[39m+\u001b[39;49m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__srv \u001b[39m+\u001b[39;49m \u001b[39m\"\u001b[39;49m\u001b[39m._tcp.\u001b[39;49m\u001b[39m\"\u001b[39;49m \u001b[39m+\u001b[39;49m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__fqdn, \u001b[39m\"\u001b[39;49m\u001b[39mSRV\u001b[39;49m\u001b[39m\"\u001b[39;49m, lifetime\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__connect_timeout\n\u001b[1;32m     99\u001b[0m     )\n\u001b[1;32m    100\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymongo/srv_resolver.py:45\u001b[0m, in \u001b[0;36m_resolve\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     43\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mhasattr\u001b[39m(resolver, \u001b[39m\"\u001b[39m\u001b[39mresolve\u001b[39m\u001b[39m\"\u001b[39m):\n\u001b[1;32m     44\u001b[0m     \u001b[39m# dnspython >= 2\u001b[39;00m\n\u001b[0;32m---> 45\u001b[0m     \u001b[39mreturn\u001b[39;00m resolver\u001b[39m.\u001b[39;49mresolve(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m     46\u001b[0m \u001b[39m# dnspython 1.X\u001b[39;00m\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dns/resolver.py:1565\u001b[0m, in \u001b[0;36mresolve\u001b[0;34m(qname, rdtype, rdclass, tcp, source, raise_on_no_answer, source_port, lifetime, search)\u001b[0m\n\u001b[1;32m   1556\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Query nameservers to find the answer to the question.\u001b[39;00m\n\u001b[1;32m   1557\u001b[0m \n\u001b[1;32m   1558\u001b[0m \u001b[39mThis is a convenience function that uses the default resolver\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1562\u001b[0m \u001b[39mparameters.\u001b[39;00m\n\u001b[1;32m   1563\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m-> 1565\u001b[0m \u001b[39mreturn\u001b[39;00m get_default_resolver()\u001b[39m.\u001b[39;49mresolve(\n\u001b[1;32m   1566\u001b[0m     qname,\n\u001b[1;32m   1567\u001b[0m     rdtype,\n\u001b[1;32m   1568\u001b[0m     rdclass,\n\u001b[1;32m   1569\u001b[0m     tcp,\n\u001b[1;32m   1570\u001b[0m     source,\n\u001b[1;32m   1571\u001b[0m     raise_on_no_answer,\n\u001b[1;32m   1572\u001b[0m     source_port,\n\u001b[1;32m   1573\u001b[0m     lifetime,\n\u001b[1;32m   1574\u001b[0m     search,\n\u001b[1;32m   1575\u001b[0m )\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dns/resolver.py:1321\u001b[0m, in \u001b[0;36mResolver.resolve\u001b[0;34m(self, qname, rdtype, rdclass, tcp, source, raise_on_no_answer, source_port, lifetime, search)\u001b[0m\n\u001b[1;32m   1320\u001b[0m     time\u001b[39m.\u001b[39msleep(backoff)\n\u001b[0;32m-> 1321\u001b[0m timeout \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_compute_timeout(start, lifetime, resolution\u001b[39m.\u001b[39;49merrors)\n\u001b[1;32m   1322\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dns/resolver.py:1075\u001b[0m, in \u001b[0;36mBaseResolver._compute_timeout\u001b[0;34m(self, start, lifetime, errors)\u001b[0m\n\u001b[1;32m   1074\u001b[0m \u001b[39mif\u001b[39;00m duration \u001b[39m>\u001b[39m\u001b[39m=\u001b[39m lifetime:\n\u001b[0;32m-> 1075\u001b[0m     \u001b[39mraise\u001b[39;00m LifetimeTimeout(timeout\u001b[39m=\u001b[39mduration, errors\u001b[39m=\u001b[39merrors)\n\u001b[1;32m   1076\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mmin\u001b[39m(lifetime \u001b[39m-\u001b[39m duration, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mtimeout)\n",
      "\u001b[0;31mLifetimeTimeout\u001b[0m: The resolution lifetime expired after 21.607 seconds: Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mConfigurationError\u001b[0m                        Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[7], line 9\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mpandas\u001b[39;00m \u001b[39mas\u001b[39;00m \u001b[39mpd\u001b[39;00m\n\u001b[1;32m      8\u001b[0m \u001b[39m# Connect to MongoDB\u001b[39;00m\n\u001b[0;32m----> 9\u001b[0m client \u001b[39m=\u001b[39m MongoClient(\n\u001b[1;32m     10\u001b[0m     \u001b[39m\"\u001b[39;49m\u001b[39mmongodb+srv://new_user:skipper1007@cluster0.t3cyiey.mongodb.net/\u001b[39;49m\u001b[39m\"\u001b[39;49m)\n\u001b[1;32m     11\u001b[0m db \u001b[39m=\u001b[39m client\u001b[39m.\u001b[39mget_database(\u001b[39m'\u001b[39m\u001b[39muser\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m     12\u001b[0m record \u001b[39m=\u001b[39m db\u001b[39m.\u001b[39mdatabase_apis\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymongo/mongo_client.py:766\u001b[0m, in \u001b[0;36mMongoClient.__init__\u001b[0;34m(self, host, port, document_class, tz_aware, connect, type_registry, **kwargs)\u001b[0m\n\u001b[1;32m    762\u001b[0m \u001b[39mif\u001b[39;00m timeout \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    763\u001b[0m     timeout \u001b[39m=\u001b[39m common\u001b[39m.\u001b[39mvalidate_timeout_or_none_or_zero(\n\u001b[1;32m    764\u001b[0m         keyword_opts\u001b[39m.\u001b[39mcased_key(\u001b[39m\"\u001b[39m\u001b[39mconnecttimeoutms\u001b[39m\u001b[39m\"\u001b[39m), timeout\n\u001b[1;32m    765\u001b[0m     )\n\u001b[0;32m--> 766\u001b[0m res \u001b[39m=\u001b[39m uri_parser\u001b[39m.\u001b[39;49mparse_uri(\n\u001b[1;32m    767\u001b[0m     entity,\n\u001b[1;32m    768\u001b[0m     port,\n\u001b[1;32m    769\u001b[0m     validate\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[1;32m    770\u001b[0m     warn\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[1;32m    771\u001b[0m     normalize\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    772\u001b[0m     connect_timeout\u001b[39m=\u001b[39;49mtimeout,\n\u001b[1;32m    773\u001b[0m     srv_service_name\u001b[39m=\u001b[39;49msrv_service_name,\n\u001b[1;32m    774\u001b[0m     srv_max_hosts\u001b[39m=\u001b[39;49msrv_max_hosts,\n\u001b[1;32m    775\u001b[0m )\n\u001b[1;32m    776\u001b[0m seeds\u001b[39m.\u001b[39mupdate(res[\u001b[39m\"\u001b[39m\u001b[39mnodelist\u001b[39m\u001b[39m\"\u001b[39m])\n\u001b[1;32m    777\u001b[0m username \u001b[39m=\u001b[39m res[\u001b[39m\"\u001b[39m\u001b[39musername\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39mor\u001b[39;00m username\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymongo/uri_parser.py:556\u001b[0m, in \u001b[0;36mparse_uri\u001b[0;34m(uri, default_port, validate, warn, normalize, connect_timeout, srv_service_name, srv_max_hosts)\u001b[0m\n\u001b[1;32m    554\u001b[0m connect_timeout \u001b[39m=\u001b[39m connect_timeout \u001b[39mor\u001b[39;00m options\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39mconnectTimeoutMS\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    555\u001b[0m dns_resolver \u001b[39m=\u001b[39m _SrvResolver(fqdn, connect_timeout, srv_service_name, srv_max_hosts)\n\u001b[0;32m--> 556\u001b[0m nodes \u001b[39m=\u001b[39m dns_resolver\u001b[39m.\u001b[39;49mget_hosts()\n\u001b[1;32m    557\u001b[0m dns_options \u001b[39m=\u001b[39m dns_resolver\u001b[39m.\u001b[39mget_options()\n\u001b[1;32m    558\u001b[0m \u001b[39mif\u001b[39;00m dns_options:\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymongo/srv_resolver.py:131\u001b[0m, in \u001b[0;36m_SrvResolver.get_hosts\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    130\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget_hosts\u001b[39m(\u001b[39mself\u001b[39m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m List[Tuple[\u001b[39mstr\u001b[39m, Any]]:\n\u001b[0;32m--> 131\u001b[0m     _, nodes \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_get_srv_response_and_hosts(\u001b[39mTrue\u001b[39;49;00m)\n\u001b[1;32m    132\u001b[0m     \u001b[39mreturn\u001b[39;00m nodes\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymongo/srv_resolver.py:111\u001b[0m, in \u001b[0;36m_SrvResolver._get_srv_response_and_hosts\u001b[0;34m(self, encapsulate_errors)\u001b[0m\n\u001b[1;32m    108\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_get_srv_response_and_hosts\u001b[39m(\n\u001b[1;32m    109\u001b[0m     \u001b[39mself\u001b[39m, encapsulate_errors: \u001b[39mbool\u001b[39m\n\u001b[1;32m    110\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Tuple[resolver\u001b[39m.\u001b[39mAnswer, List[Tuple[\u001b[39mstr\u001b[39m, Any]]]:\n\u001b[0;32m--> 111\u001b[0m     results \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_resolve_uri(encapsulate_errors)\n\u001b[1;32m    113\u001b[0m     \u001b[39m# Construct address tuples\u001b[39;00m\n\u001b[1;32m    114\u001b[0m     nodes \u001b[39m=\u001b[39m [\n\u001b[1;32m    115\u001b[0m         (maybe_decode(res\u001b[39m.\u001b[39mtarget\u001b[39m.\u001b[39mto_text(omit_final_dot\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)), res\u001b[39m.\u001b[39mport) \u001b[39mfor\u001b[39;00m res \u001b[39min\u001b[39;00m results\n\u001b[1;32m    116\u001b[0m     ]\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymongo/srv_resolver.py:105\u001b[0m, in \u001b[0;36m_SrvResolver._resolve_uri\u001b[0;34m(self, encapsulate_errors)\u001b[0m\n\u001b[1;32m    103\u001b[0m         \u001b[39mraise\u001b[39;00m\n\u001b[1;32m    104\u001b[0m     \u001b[39m# Else, raise all errors as ConfigurationError.\u001b[39;00m\n\u001b[0;32m--> 105\u001b[0m     \u001b[39mraise\u001b[39;00m ConfigurationError(\u001b[39mstr\u001b[39m(exc))\n\u001b[1;32m    106\u001b[0m \u001b[39mreturn\u001b[39;00m results\n",
      "\u001b[0;31mConfigurationError\u001b[0m: The resolution lifetime expired after 21.607 seconds: Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out.; Server Do53:10.100.56.27@53 answered The DNS operation timed out.; Server Do53:10.100.56.25@53 answered The DNS operation timed out."
     ]
    }
   ],
   "source": [
    "import json\n",
    "from sklearn.metrics.pairwise import linear_kernel\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from pymongo import MongoClient\n",
    "import sys\n",
    "import pandas as pd\n",
    "\n",
    "# Connect to MongoDB\n",
    "client = MongoClient(\n",
    "    \"mongodb+srv://new_user:skipper1007@cluster0.t3cyiey.mongodb.net/\")\n",
    "db = client.get_database('user')\n",
    "record = db.database_apis\n",
    "\n",
    "# Retrieve data from MongoDB\n",
    "data = list(record.find())\n",
    "df = pd.DataFrame(data)\n",
    "\n",
    "# Drop unnecessary columns\n",
    "df.drop(['video_url'], axis=1, inplace=True)\n",
    "df.dropna(subset=['content'], inplace=True)\n",
    "\n",
    "# Get user history from command line arguments\n",
    "hist_fetch = sys.argv[1:]\n",
    "user_history = [str(item) for item in hist_fetch]\n",
    "\n",
    "# TF-IDF Vectorization\n",
    "tfidf_vectorizer = TfidfVectorizer(stop_words='english')\n",
    "tfidf_matrix = tfidf_vectorizer.fit_transform(df['content'])\n",
    "\n",
    "# Calculate cosine similarity between user history and all articles\n",
    "user_history_vector = tfidf_vectorizer.transform(user_history)\n",
    "cosine_similarities = linear_kernel(user_history_vector, tfidf_matrix)\n",
    "\n",
    "# Get indices of similar articles\n",
    "similar_articles_indices = cosine_similarities.argsort()[0][::-1]\n",
    "\n",
    "# Recommend top N articles\n",
    "top_n = 5\n",
    "recommended_articles = []\n",
    "\n",
    "for i in range(top_n):\n",
    "    index = similar_articles_indices[i]\n",
    "    recommended_articles.append({\n",
    "        'title': df['title'][index],\n",
    "        'link': df['link'][index],\n",
    "        'keywords': df['keywords'][index],\n",
    "        'creator': df['creator'][index],\n",
    "        'description': df['description'][index],\n",
    "        'content': df['content'][index],\n",
    "        'pubDate': df['pubDate'][index],\n",
    "        'image_url': df['image_url'][index],\n",
    "        'country': df['country'][index],\n",
    "        'category': df['category'][index],\n",
    "        'language': df['language'][index]\n",
    "    })\n",
    "\n",
    "# Print recommended articles\n",
    "print(f\"Recommended articles for the user based on their reading history:\")\n",
    "for i, article in enumerate(recommended_articles):\n",
    "    print(\n",
    "        f\"{i + 1}. Title: {article['title']}\\n   Content: {article['content']}\\n\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pymongo\n",
      "  Obtaining dependency information for pymongo from https://files.pythonhosted.org/packages/de/67/949da6f882723be8ca8ef63678d7f999b4d9c235c656c0376ea8b6c041d6/pymongo-4.5.0-cp311-cp311-macosx_10_9_universal2.whl.metadata\n",
      "  Downloading pymongo-4.5.0-cp311-cp311-macosx_10_9_universal2.whl.metadata (22 kB)\n",
      "Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)\n",
      "  Obtaining dependency information for dnspython<3.0.0,>=1.16.0 from https://files.pythonhosted.org/packages/f6/b4/0a9bee52c50f226a3cbfb54263d02bb421c7f2adc136520729c2c689c1e5/dnspython-2.4.2-py3-none-any.whl.metadata\n",
      "  Downloading dnspython-2.4.2-py3-none-any.whl.metadata (4.9 kB)\n",
      "Downloading pymongo-4.5.0-cp311-cp311-macosx_10_9_universal2.whl (529 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m529.4/529.4 kB\u001b[0m \u001b[31m4.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading dnspython-2.4.2-py3-none-any.whl (300 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m300.4/300.4 kB\u001b[0m \u001b[31m6.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: dnspython, pymongo\n",
      "Successfully installed dnspython-2.4.2 pymongo-4.5.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.11.4 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
